In [5]:
import pandas as pd
import numpy as np
import time
import requests
import datetime as dt

pd.set_option('display.max_columns', None)

6-Month Average TVL

In [2]:
#DefiLlama https://defillama.com/protocols/dexes 
lma = pd.read_csv("https://api.llama.fi/dataset/orca.csv")

In [3]:
lma

,Unnamed: 0,Date,Timestamp,Orca,Orca.1,Orca.2,Orca.3,Orca.4,Orca.5,Orca.6,Orca.7,Orca.8,Orca.9,Orca.10,Orca.11,Orca.12,Orca.13,Orca.14,Orca.15,Orca.16,Orca.17,Orca.18,Orca.19,Orca.20,Orca.21,Orca.22,Orca.23,Orca.24,Orca.25,Orca.26,Orca.27,Orca.28,Orca.29,Orca.30,Orca.31,Orca.32,Orca.33,Orca.34,Orca.35,Orca.36,Orca.37,Orca.38,Orca.39,Orca.40,Orca.41,Orca.42,Orca.43,Orca.44,Orca.45
0,NaN,NaN,NaN,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes,Dexes
1,NaN,NaN,NaN,Total,solana,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,solana,solana,solana,solana,solana,solana,solana,solana,solana,solana,solana,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,solana,solana,solana,solana,solana,solana,solana,solana,solana,solana,solana
2,NaN,NaN,NaN,TVL,TVL,Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens(USD),Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens,Tokens
3,NaN,NaN,NaN,NaN,NaN,ethereum,kin,raydium,rope-token,tether,solana,usd-coin,serum,bitcoin,ftx-token,undefined,ethereum,kin,raydium,rope-token,tether,solana,usd-coin,serum,bitcoin,ftx-token,undefined,ethereum,kin,raydium,rope-token,tether,solana,usd-coin,serum,bitcoin,ftx-token,undefined,ethereum,kin,raydium,rope-token,tether,solana,usd-coin,serum,bitcoin,ftx-token,undefined
4,NaN,14/04/2021,1.618358e+09,24980014.778269257,24980014.778269257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,NaN,18/09/2022,1.663459e+09,87877648.63897389,87877648.63897389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
525,NaN,19/09/2022,1.663546e+09,84564015.14506584,84564015.14506584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526,NaN,20/09/2022,1.663632e+09,84951090.47661683,84951090.47661683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,NaN,21/09/2022,1.663718e+09,84906195.59902678,84906195.59902678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528,NaN,22/09/2022,1.663805e+09,82347441.99675134,82347441.99675134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
lma.iloc[:,3]

0                   Dexes
1                   Total
2                     TVL
3                     NaN
4      24980014.778269257
              ...
524     87877648.63897389
525     84564015.14506584
526     84951090.47661683
527     84906195.59902678
528     82347441.99675134
Name: Orca, Length: 529, dtype: object

In [5]:
#Just eth currently can take total by changing the header
lma.iloc[-183:, 3].astype(float).mean()

204637144.2789848

In [6]:
headers = {# Chrome 83 Mac
    "Connection": "keep-alive",
    "DNT": "1",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "Sec-Fetch-Site": "none",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Dest": "document",
    "Referer": "https://www.google.com/",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8"}

In [7]:
#active users
url = "https://brew.hellomoon.io/api/aggregations/defi-token-by-active-user-count?timeRangeFilter=all&tokenFilter=orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE"

In [8]:
resp = requests.get(url, headers = headers)

In [11]:
data =resp.json()

In [15]:
df = pd.DataFrame(data['data'])

In [17]:
df['y'].head(183).mean()

2922.2349726775956

In [18]:
url = "https://nomics.com/data/exchange-volume-history?convert=USD&exchange=orca&interval=all"

In [19]:
resp = requests.get(url)

In [21]:
data = resp.json()

In [23]:
df = pd.DataFrame(data['items'])

In [27]:
df['volume'].astype(float).tail(183).mean()

63823324.53551912